import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Check, Sparkles, Image, Utensils, Clock, MapPin, Tag, PartyPopper } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { loadRestaurantDraft, compileRestaurantProfile, clearDraft } from '@/utils/onboardingStore';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { supabase } from '@/integrations/supabase/client';

const ReviewAndSubmit = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [compiled, setCompiled] = useState<ReturnType<typeof compileRestaurantProfile> | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);

  useEffect(() => {
    const draft = loadRestaurantDraft();
    const result = compileRestaurantProfile(draft);
    setCompiled(result);
  }, []);

  const handlePublish = useCallback(async () => {
    if (!compiled) return;
    
    setIsSubmitting(true);
    
    try {
      // Get current user
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        toast({
          title: "Authentication Required",
          description: "Please log in to publish your restaurant",
          variant: "destructive"
        });
        navigate('/auth');
        return;
      }

      const userId = session.user.id;
      const { restaurant, menu } = compiled;

      // Insert restaurant into Supabase
      const { data: restaurantData, error: restaurantError } = await supabase
        .from('restaurants')
        .insert([{
          user_id: userId,
          name: restaurant.name,
          description: restaurant.description,
          cuisine_type: restaurant.cuisine_type || 'General',
          brand_style: 'modern',
          primary_color: '#8B5CF6',
          secondary_color: '#10B981',
          phone: restaurant.phone || null,
          address: null,
          city: restaurant.region || null,
          latitude: restaurant.latitude ? Number(restaurant.latitude) : null,
          longitude: restaurant.longitude ? Number(restaurant.longitude) : null,
          logo_url: restaurant.logo_url || null,
          hours: restaurant.hours as any || null,
          is_open: true,
        }])
        .select()
        .single();

      if (restaurantError) {
        throw restaurantError;
      }

      // Insert menu items if any exist
      const allMenuItems = menu.flatMap(category => 
        category.items.map(item => ({
          restaurant_id: restaurantData.id,
          name: item.name,
          description: item.description || null,
          price: item.price,
          category: category.name,
          image_url: item.image_url || null,
          available: true,
        }))
      );

      if (allMenuItems.length > 0) {
        const { error: menuError } = await supabase
          .from('menu_items')
          .insert(allMenuItems);

        if (menuError) {
          console.error('Menu insert error:', menuError);
          // Don't fail the whole publish if menu fails
        }
      }

      setShowConfetti(true);
      
      toast({
        title: "🎉 Restaurant Published!",
        description: "Your restaurant is now live on Outa",
      });
      
      // Clear draft and redirect after animation
      setTimeout(() => {
        clearDraft();
        navigate('/');
      }, 3000);

    } catch (error: any) {
      console.error('Publish error:', error);
      toast({
        title: "Failed to publish",
        description: error.message || "Something went wrong. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsSubmitting(false);
    }
  }, [compiled, navigate, toast]);

  if (!compiled) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-background via-background/95 to-secondary/30 flex items-center justify-center">
        <div className="w-12 h-12 rounded-full border-4 border-purple/30 border-t-purple animate-spin" />
      </div>
    );
  }

  const { restaurant, gallery, menu, autoGeneratedTags, completeness } = compiled;
  const totalMenuItems = menu.reduce((sum, cat) => sum + cat.items.length, 0);

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background/95 to-secondary/30 pb-32 relative overflow-hidden">
      {/* Confetti Effect */}
      {showConfetti && (
        <div className="fixed inset-0 z-50 pointer-events-none">
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center animate-scale-in">
              <PartyPopper className="h-24 w-24 text-purple mx-auto mb-4 animate-bounce" />
              <h2 className="text-3xl font-bold text-foreground mb-2">You're Live! 🎉</h2>
              <p className="text-muted-foreground">Redirecting to home...</p>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="sticky top-0 z-40 bg-background/80 backdrop-blur-xl border-b border-border/50">
        <div className="px-4 py-4">
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => navigate('/restaurant/onboarding/hours')}
              className="rounded-full"
              disabled={isSubmitting}
            >
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div className="flex-1">
              <p className="text-xs text-purple font-medium">Step 6 of 6</p>
              <h1 className="text-xl font-bold text-foreground">Review & Publish</h1>
            </div>
          </div>
        </div>
      </div>

      <div className="px-4 py-6 space-y-6">
        {/* Completeness Score */}
        <Card className="p-6 bg-gradient-to-br from-purple/10 to-neon-pink/5 border-purple/20 animate-slide-up">
          <div className="flex items-center gap-4 mb-4">
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-purple to-neon-pink flex items-center justify-center shadow-lg shadow-purple/30">
              <Sparkles className="h-7 w-7 text-white" />
            </div>
            <div className="flex-1">
              <h2 className="text-lg font-bold text-foreground">{restaurant.name || 'Your Restaurant'}</h2>
              <p className="text-sm text-muted-foreground">Profile completeness</p>
            </div>
            <div className="text-right">
              <span className="text-2xl font-bold text-purple">{completeness}%</span>
            </div>
          </div>
          <Progress value={completeness} className="h-2 bg-secondary/50" />
        </Card>

        {/* Cover & Logo Preview */}
        {(restaurant.cover_url || restaurant.logo_url) && (
          <Card className="overflow-hidden animate-slide-up" style={{ animationDelay: '50ms' }}>
            {restaurant.cover_url && (
              <div className="relative h-40">
                <img src={restaurant.cover_url} alt="Cover" className="w-full h-full object-cover" />
                {restaurant.logo_url && (
                  <div className="absolute -bottom-8 left-4">
                    <img 
                      src={restaurant.logo_url} 
                      alt="Logo" 
                      className="w-16 h-16 rounded-2xl border-4 border-background object-cover shadow-lg"
                    />
                  </div>
                )}
              </div>
            )}
            <div className="p-4 pt-10">
              <h3 className="font-semibold text-foreground">{restaurant.name}</h3>
              <p className="text-sm text-muted-foreground line-clamp-2">{restaurant.description}</p>
            </div>
          </Card>
        )}

        {/* Restaurant Info */}
        <Card className="p-4 animate-slide-up" style={{ animationDelay: '100ms' }}>
          <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
            <MapPin className="h-4 w-4 text-purple" />
            Details
          </h3>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Cuisine</span>
              <span className="text-foreground">{restaurant.cuisine_type || 'Not set'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Region</span>
              <span className="text-foreground">{restaurant.region || 'Not set'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Price Level</span>
              <span className="text-foreground">{restaurant.price_level}</span>
            </div>
          </div>
        </Card>

        {/* Gallery Summary */}
        <Card className="p-4 animate-slide-up" style={{ animationDelay: '150ms' }}>
          <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
            <Image className="h-4 w-4 text-purple" />
            Gallery ({gallery.length} photos)
          </h3>
          {gallery.length > 0 ? (
            <div className="flex gap-2 overflow-x-auto pb-2 -mx-4 px-4">
              {gallery.slice(0, 4).map((img, i) => (
                <img 
                  key={img.id}
                  src={img.url}
                  alt={`Gallery ${i + 1}`}
                  className="w-16 h-16 rounded-xl object-cover flex-shrink-0"
                />
              ))}
              {gallery.length > 4 && (
                <div className="w-16 h-16 rounded-xl bg-secondary flex items-center justify-center flex-shrink-0">
                  <span className="text-sm text-muted-foreground">+{gallery.length - 4}</span>
                </div>
              )}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No photos added</p>
          )}
        </Card>

        {/* Menu Summary */}
        <Card className="p-4 animate-slide-up" style={{ animationDelay: '200ms' }}>
          <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
            <Utensils className="h-4 w-4 text-purple" />
            Menu ({menu.length} categories, {totalMenuItems} items)
          </h3>
          <div className="space-y-2">
            {menu.filter(cat => cat.items.length > 0).map(cat => (
              <div key={cat.name} className="flex justify-between text-sm">
                <span className="text-muted-foreground">{cat.name}</span>
                <span className="text-foreground">{cat.items.length} items</span>
              </div>
            ))}
          </div>
        </Card>

        {/* AI Generated Tags */}
        {autoGeneratedTags.length > 0 && (
          <Card className="p-4 bg-purple/5 border-purple/20 animate-slide-up" style={{ animationDelay: '250ms' }}>
            <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
              <Tag className="h-4 w-4 text-purple" />
              <Sparkles className="h-3 w-3 text-purple" />
              AI-Generated Tags
            </h3>
            <div className="flex flex-wrap gap-2">
              {autoGeneratedTags.map(tag => (
                <Badge 
                  key={tag.label}
                  variant="outline"
                  className="border-purple/30 text-purple"
                >
                  {tag.label}
                </Badge>
              ))}
            </div>
          </Card>
        )}

        {/* Hours Summary */}
        <Card className="p-4 animate-slide-up" style={{ animationDelay: '300ms' }}>
          <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
            <Clock className="h-4 w-4 text-purple" />
            Opening Hours
          </h3>
          <div className="space-y-1 text-sm">
            {Object.entries(restaurant.hours || {}).slice(0, 3).map(([day, h]: [string, any]) => (
              <div key={day} className="flex justify-between">
                <span className="text-muted-foreground capitalize">{day}</span>
                <span className="text-foreground">
                  {h.closed ? 'Closed' : `${h.open} - ${h.close}`}
                </span>
              </div>
            ))}
            <p className="text-xs text-muted-foreground pt-1">+ more...</p>
          </div>
        </Card>
      </div>

      {/* Footer */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-background/80 backdrop-blur-xl border-t border-border/50">
        <Button
          onClick={handlePublish}
          disabled={isSubmitting || completeness < 50}
          className={cn(
            "w-full h-14 text-lg font-semibold rounded-xl transition-all",
            isSubmitting 
              ? "bg-purple/50" 
              : "bg-gradient-to-r from-purple to-neon-pink shadow-lg shadow-purple/30"
          )}
        >
          {isSubmitting ? (
            <div className="flex items-center gap-3">
              <div className="w-5 h-5 rounded-full border-2 border-white/30 border-t-white animate-spin" />
              Publishing...
            </div>
          ) : (
            <>
              <Sparkles className="h-5 w-5 mr-2" />
              Publish to Outa
            </>
          )}
        </Button>
        {completeness < 50 && (
          <p className="text-xs text-center text-muted-foreground mt-2">
            Complete at least 50% of your profile to publish
          </p>
        )}
      </div>
    </div>
  );
};

export default ReviewAndSubmit;
